version: '2'
services:
  hbe-python-data:
    build:
      context: .
      dockerfile: hbe-python-data.dockerfile
    ports:
      - "8888:8888"
    volumes:
      # CHANGE ~/dev to your project path on the host machine
      - ~/dev:/data
